### ISSUE TITLE
Can I access AB remotely via this addon if I already pay for nabu casa subscription which exposes it outside my network?

### ISSUE THREAD

**Issue by akshay7394** [sztupy/hassio-actualbudget#5]
As it says in the title, can I access AB remotely via this addon if I already pay for nabu casa subscription which exposes it outside my network? 

I would love to just use the existing SSL setup and extend it to this addon too, but I'm not sure how to do that. It seems since the nabu casa url accesses port 8123 directly it may not be possible, but i thought I'd check here to confirm? Any way I can make it so that i can access Actual via something like `url.nabu.casa/actualbudget`?

Here are the documentation links related to Addons and using Ingress:
# https://www.home-assistant.io/blog/2019/04/15/hassio-ingress/
# https://developers.home-assistant.io/docs/add-ons/presentation/#ingress

**Comment by hdsheena** [comment]
I'm in the same boat, asking this question plus "if I do the other setup/config for this, will it break my nabu?"

**Comment by sztupy** [comment]
Unfortunately I'm not a nabu subscriber so cannot check. THe ingress settings are set up properly in the plugin, so ff Nabu properly routes somehow to other ingresses, and they run on the root of the domain, and the connection is HTTPS then it should definitely work. Otherwise it might work with some caveats. Unfortunately I'm unable to confirm as I'm not subscribed to nabu casa or other similar services

**Comment by akshay7394** [comment]
Based on my experience (and based on the indicator being missing on the
add-on listing) I guess ingress isn't being detected as supported, if
you've implemented it it's not being detected by hass for some reason. I've
attached a screenshot of actual budget vs studio code server to illustrate
what I mean (so it's not specific tu having the subscription).

**Comment by sztupy** [comment]
I had a look and unfortunately due to actual budget not using relative URLs this is not supported right now. This is something that you would need to raise with the ActualBudget development team on their github to change their website to always use relative URLs when referencing files instead of absolute ones they do right now. This is not a trivial change, but doable, I have found another project that just did the same change to support HA ingress recently: https://github.com/blakeblackshear/frigate/issues/541

If you raise this in the ActualBudget github and they do fix this at some point (you can point them to this bugreport as well as the frigate issue I linked above), I'm happy to update the config to use ingress instead of the legacy webui.

**Comment by akshay7394** [comment]
Noted, thanks for looking into it! I'll raise a ticket with them and see how it goes :)
